name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: RamonSantos10
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: "#8B5CF6"
          color_snake: "#8B5CF6"
          color_dots: "#0A0C10, #8B5CF6, #8B5CF6, #8B5CF6, #8B5CF6"

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}